PROJECT         := CalaosPLC
DEVICES         := NUCLEO_F411RE NUCLEO_L053R8
GCC4MBED_DIR    := ../gcc4mbed/
GCC4MBED_TYPE	:= Debug
GCFLAGS 	:= -Werror
CONFIG		:= configs/mbed_config.json
GAFLAGS 	:= -DCONFIG_PATH='"$(CONFIG)"'
EXCLUDE		:= HAL/linux
NO_FLOAT_SCANF	:= 1

NUCLEO_F411RE/core/incconfig.o: $(CONFIG)
NUCLEO_L053R8/core/incconfig.o: $(CONFIG)

include $(GCC4MBED_DIR)/build/gcc4mbed.mk
